services:
  - type: web
    name: calculo-caudales
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 4000
      - key: LOG_LEVEL
        value: Information
      - key: API_KEY
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: CORA_API_URL
        sync: false
      - key: CORA_API_URL_LA_PERLA
        sync: false
      - key: CORA_API_CANTIDAD
        value: 72
      - key: CORA_SYNC_MINUTES
        value: 10
      - key: CORA_SYNC_ON_START
        value: true
      - key: ESCORRENTIA_COEFICIENTE
        value: 0.65
      - key: ESCORRENTIA_AREA_M2
        sync: false
      - key: CAFETAL_CURVA_NUMERO
        value: 75
      - key: LA_PERLA_CURVA_NUMERO
        value: 75
      - key: CAFETAL_LATITUD
        value: 15.22553
      - key: CAFETAL_LONGITUD
        value: -90.11064
      - key: LA_PERLA_LATITUD
        value: 15.640000
      - key: LA_PERLA_LONGITUD
        value: -90.069444
